// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeachTrack.Model.DBContext;

#nullable disable

namespace TeachTrack.Model.Migrations
{
    [DbContext(typeof(TeachTrackContext))]
    [Migration("20240502192134_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("sequence_subject")
                .StartsAt(11003L)
                .IncrementsBy(3);

            modelBuilder.HasSequence("squence_student")
                .StartsAt(21000L)
                .IncrementsBy(2);

            modelBuilder.HasSequence("studentsequence")
                .StartsAt(21000L)
                .IncrementsBy(2);

            modelBuilder.Entity("TeachTrack.Model.Models.Career", b =>
                {
                    b.Property<int>("Careerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("careerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Careerid"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Shortname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("shortname");

                    b.Property<string>("Status")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.HasKey("Careerid")
                        .HasName("Career_pkey");

                    b.ToTable("Career", (string)null);
                });

            modelBuilder.Entity("TeachTrack.Model.Models.Degree", b =>
                {
                    b.Property<int>("Degreeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("degreeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Degreeid"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Shortname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("shortname");

                    b.HasKey("Degreeid")
                        .HasName("Degree_pkey");

                    b.ToTable("Degree", (string)null);
                });

            modelBuilder.Entity("TeachTrack.Model.Models.Schedule", b =>
                {
                    b.Property<int>("Scheduleid")
                        .HasColumnType("integer")
                        .HasColumnName("scheduleid");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<int>("Subjectid")
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("TeachTrack.Model.Models.Semester", b =>
                {
                    b.Property<int>("Semesterid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("semesterid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Semesterid"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Shortname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("shortname");

                    b.HasKey("Semesterid")
                        .HasName("Semester_pkey");

                    b.ToTable("Semester", (string)null);
                });

            modelBuilder.Entity("TeachTrack.Model.Models.Student", b =>
                {
                    b.Property<int>("Studentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("studentid")
                        .HasDefaultValueSql("nextval('squence_student'::regclass)");

                    b.Property<int?>("Careerid")
                        .HasColumnType("integer")
                        .HasColumnName("careerid");

                    b.Property<int?>("Degreeid")
                        .HasColumnType("integer")
                        .HasColumnName("degreeid");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Score")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("score");

                    b.Property<int?>("Semesterid")
                        .HasColumnType("integer")
                        .HasColumnName("semesterid");

                    b.Property<string>("Status")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.HasKey("Studentid")
                        .HasName("Student_pkey");

                    b.HasIndex("Careerid");

                    b.HasIndex("Degreeid");

                    b.HasIndex("Semesterid");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("TeachTrack.Model.Models.Subject", b =>
                {
                    b.Property<int>("Subjectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subjectid")
                        .HasDefaultValueSql("nextval('sequence_subject'::regclass)");

                    b.Property<int?>("Careerid")
                        .HasColumnType("integer")
                        .HasColumnName("careerid");

                    b.Property<int?>("Degreeid")
                        .HasColumnType("integer")
                        .HasColumnName("degreeid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("name");

                    b.Property<int?>("Semesterid")
                        .HasColumnType("integer")
                        .HasColumnName("semesterid");

                    b.Property<string>("Shortname")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("shortname");

                    b.Property<string>("Status")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.HasKey("Subjectid")
                        .HasName("Subject_pkey");

                    b.HasIndex("Careerid");

                    b.HasIndex("Degreeid");

                    b.HasIndex("Semesterid");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("TeachTrack.Model.Models.SubjectSchedule", b =>
                {
                    b.Property<int>("Scheduleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("scheduleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Scheduleid"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("schedule");

                    b.Property<string>("Status")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<int>("Subjectid")
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    b.HasKey("Scheduleid")
                        .HasName("SubjectSchedule_pkey");

                    b.ToTable("SubjectSchedule", (string)null);
                });

            modelBuilder.Entity("TeachTrack.Model.Models.Student", b =>
                {
                    b.HasOne("TeachTrack.Model.Models.Career", "Career")
                        .WithMany("Students")
                        .HasForeignKey("Careerid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_student2");

                    b.HasOne("TeachTrack.Model.Models.Degree", "Degree")
                        .WithMany("Students")
                        .HasForeignKey("Degreeid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_student1");

                    b.HasOne("TeachTrack.Model.Models.Semester", "Semester")
                        .WithMany("Students")
                        .HasForeignKey("Semesterid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_student3");

                    b.Navigation("Career");

                    b.Navigation("Degree");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("TeachTrack.Model.Models.Subject", b =>
                {
                    b.HasOne("TeachTrack.Model.Models.Career", "Career")
                        .WithMany("Subjects")
                        .HasForeignKey("Careerid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_subject2");

                    b.HasOne("TeachTrack.Model.Models.Degree", "Degree")
                        .WithMany("Subjects")
                        .HasForeignKey("Degreeid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_subject1");

                    b.HasOne("TeachTrack.Model.Models.Semester", "Semester")
                        .WithMany("Subjects")
                        .HasForeignKey("Semesterid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_subject3");

                    b.Navigation("Career");

                    b.Navigation("Degree");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("TeachTrack.Model.Models.Career", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("TeachTrack.Model.Models.Degree", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("TeachTrack.Model.Models.Semester", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
